create table "public"."expenses_categories" (
    "id" bigint generated by default as identity not null,
    "expense_id" bigint not null,
    "category_id" bigint not null,
    "home_id" uuid not null
);

alter table "public"."expenses_categories" enable row level security;

CREATE UNIQUE INDEX expenses_categories_pkey ON public.expenses_categories USING btree (id);

alter table "public"."expenses_categories"
add constraint "expenses_categories_pkey" PRIMARY KEY using index "expenses_categories_pkey";

alter table "public"."expenses_categories"
add constraint "expenses_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.expense_categories (id) ON DELETE CASCADE not valid;

alter table "public"."expenses_categories" validate constraint "expenses_categories_category_id_fkey";

alter table "public"."expenses_categories"
add constraint "expenses_categories_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES public.expenses (id) ON DELETE CASCADE not valid;

alter table "public"."expenses_categories" validate constraint "expenses_categories_expense_id_fkey";

alter table "public"."expenses_categories"
add constraint "expenses_categories_home_id_fkey" FOREIGN KEY (home_id) REFERENCES public.homes (id) ON DELETE CASCADE not valid;

alter table "public"."expenses_categories" validate constraint "expenses_categories_home_id_fkey";

alter table public.expenses_categories
add constraint expenses_categories_unique
unique (expense_id, category_id, home_id);

create policy "Users can only manage expenses related to their home" on "public"."expenses_categories" as permissive for all to authenticated using (
    (
        home_id = (
            SELECT public.get_request_home () AS get_request_home
        )
    )
);