create table "public"."expense_categories" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "parent" bigint,
    "home_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."expense_categories" enable row level security;

CREATE UNIQUE INDEX expense_categories_pkey ON public.expense_categories USING btree (id);

alter table "public"."expense_categories"
add constraint "expense_categories_pkey" PRIMARY KEY using index "expense_categories_pkey";

alter table "public"."expense_categories"
add constraint "expense_categories_home_id_fkey" FOREIGN KEY (home_id) REFERENCES public.homes (id) ON DELETE CASCADE not valid;

alter table "public"."expense_categories" validate constraint "expense_categories_home_id_fkey";

alter table "public"."expense_categories"
add constraint "expense_categories_parent_fkey" FOREIGN KEY (parent) REFERENCES public.expense_categories (id) ON DELETE CASCADE not valid;

alter table "public"."expense_categories" validate constraint "expense_categories_parent_fkey";

create policy "Users can only manage expenses categories related to their home" on "public"."expense_categories" as permissive for all to authenticated using (
    (
        home_id = (
            SELECT public.get_request_home () AS get_request_home
        )
    )
);