create table "public"."expense_details" (
    "id" bigint generated by default as identity not null,
    "article_id" bigint not null,
    "amount" numeric not null,
    "quantity" numeric not null default '1'::numeric,
    "expense_id" bigint not null,
    "home_id" uuid not null
);

alter table "public"."expense_details" enable row level security;

CREATE UNIQUE INDEX expense_details_pkey ON public.expense_details USING btree (id);

alter table "public"."expense_details"
add constraint "expense_details_pkey" PRIMARY KEY using index "expense_details_pkey";

alter table "public"."expense_details"
add constraint "expense_details_article_id_fkey" FOREIGN KEY (article_id) REFERENCES public.expense_items (id) ON DELETE CASCADE not valid;

alter table "public"."expense_details" validate constraint "expense_details_article_id_fkey";

alter table "public"."expense_details"
add constraint "expense_details_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES public.expenses (id) ON DELETE CASCADE not valid;

alter table "public"."expense_details" validate constraint "expense_details_expense_id_fkey";

alter table "public"."expense_details"
add constraint "expense_details_home_id_fkey" FOREIGN KEY (home_id) REFERENCES public.homes (id) ON DELETE CASCADE not valid;

alter table "public"."expense_details" validate constraint "expense_details_home_id_fkey";

create policy "Users can only manage expenses details related to their home" on "public"."expense_details" as permissive for all to authenticated using (
    (
        home_id = (
            SELECT public.get_request_home () AS get_request_home
        )
    )
);