create table "public"."expenses" (
    "id" bigint generated by default as identity not null,
    "date" timestamp with time zone not null,
    "name" character varying not null,
    "amount" numeric not null,
    "description" text,
    "count" numeric not null default '1'::numeric,
    "as_group" boolean not null default false,
    "home_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."expenses" enable row level security;

CREATE UNIQUE INDEX expenses_pkey ON public.expenses USING btree (id);

alter table "public"."expenses"
add constraint "expenses_pkey" PRIMARY KEY using index "expenses_pkey";

alter table "public"."expenses"
add constraint "expenses_home_id_fkey" FOREIGN KEY (home_id) REFERENCES public.homes (id) ON DELETE CASCADE not valid;

alter table "public"."expenses" validate constraint "expenses_home_id_fkey";

create policy "Users can only manage expenses related to their home" on "public"."expenses" as permissive for all to authenticated using (
    (
        home_id = (
            SELECT public.get_request_home () AS get_request_home
        )
    )
);
