create table "public"."expense_items" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "unit" character varying,
    "category_id" bigint not null,
    "home_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."expense_items" enable row level security;

CREATE UNIQUE INDEX articles_pkey ON public.expense_items USING btree (id);

alter table "public"."expense_items"
add constraint "articles_pkey" PRIMARY KEY using index "articles_pkey";

alter table "public"."expense_items"
add constraint "articles_home_id_fkey" FOREIGN KEY (home_id) REFERENCES public.homes (id) ON DELETE CASCADE not valid;

alter table "public"."expense_items" validate constraint "articles_home_id_fkey";

alter table "public"."expense_items"
add constraint "expense_items_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.expense_categories (id) ON DELETE CASCADE not valid;

alter table "public"."expense_items" validate constraint "expense_items_category_id_fkey";

create policy "Users can only manage expenses items related to their home" on "public"."expense_items" as permissive for all to authenticated using (
    (
        home_id = (
            SELECT public.get_request_home () AS get_request_home
        )
    )
);